# Generated by Django 3.0.4 on 2020-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=85)),
                ('quantity_in_store', models.IntegerField(default='1')),
                ('dealer', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('descriptions', models.TextField(blank=True)),
            ],
        ),
    ]
